Feature/update domain model
czech-radio/cro-geneea-sdk pull request #12
Opened 2022-04-29 17:58 UTC by K0F

fixes bod c 1 from #10

2022-04-29 17:59 UTC, K0F commented
..trochu bordylek, nakumulovalo se mi tam vicero commitu, ale rad bych to sloucil s mainem

2022-05-03 17:00 UTC, groundf commented on src/cro/geneea/sdk/_domain.py
> +        Function returns a tuple of Realtions from analyzed JSON.
Change `tuple of Relations` to `relations`. The type is already listed in the type signature.

2022-05-03 17:02 UTC, groundf commented on src/cro/geneea/sdk/_domain.py
> +        Function returns Account object from Analyzed JSON.
Remove the word `function`, this is a method. Maybe write simply `Returns account object from analyzed JSON.`

2022-05-03 17:03 UTC, groundf requested changes
Write tests for the account method.

2022-05-03 17:12 UTC, groundf commented
Please rebase against `main` (U r 1 commit behind).

2022-05-04 08:15 UTC, K0F commented on src/cro/geneea/sdk/_domain.py
> +        Function returns Account object from Analyzed JSON.
ok diky zaneseno

2022-05-04 08:21 UTC, K0F reviewed
ok doresim ty konfilkty a zkusim mergnout

2022-05-04 08:21 UTC, merged